services:
  envoy:
    image: envoyproxy/envoy:v1.36.2
    container_name: eas-envoy
    ports:
      - "8080:80"
      - "9901:9901"
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: ["-c", "/etc/envoy/envoy.yaml"]
    depends_on:
      - upstream
      
  upstream:
    image: mendhak/http-https-echo:33
    container_name: eas-upstream
    ports:
      - "8082:80"
    environment:
      - HTTP_PORT=80

  redis:
    image: redis:7-alpine
    container_name: eas-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: eas-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: security
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/seed-postgres.sql:/seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
