apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases

configMapGenerator:
  - name: envoy-authorization-service-config
    options:
      disableNameSuffixHash: true
    files:
      - config.yaml
      - allowed-ips.txt
      - blocked-ips.txt
